// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterWeightMap) DeepCopyInto(out *ClusterWeightMap) {
	*out = *in
	if in.NamespaceWeightMap != nil {
		in, out := &in.NamespaceWeightMap, &out.NamespaceWeightMap
		*out = make(map[string]*NamespaceWeightMap, len(*in))
		for key, val := range *in {
			var outVal *NamespaceWeightMap
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(NamespaceWeightMap)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterWeightMap.
func (in *ClusterWeightMap) DeepCopy() *ClusterWeightMap {
	if in == nil {
		return nil
	}
	out := new(ClusterWeightMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceWeightMap) DeepCopyInto(out *NamespaceWeightMap) {
	*out = *in
	if in.ServiceWeightMap != nil {
		in, out := &in.ServiceWeightMap, &out.ServiceWeightMap
		*out = make(map[string]*ServiceWeightMap, len(*in))
		for key, val := range *in {
			var outVal *ServiceWeightMap
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(ServiceWeightMap)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceWeightMap.
func (in *NamespaceWeightMap) DeepCopy() *NamespaceWeightMap {
	if in == nil {
		return nil
	}
	out := new(NamespaceWeightMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceImportWeightMap) DeepCopyInto(out *ServiceImportWeightMap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceImportWeightMap.
func (in *ServiceImportWeightMap) DeepCopy() *ServiceImportWeightMap {
	if in == nil {
		return nil
	}
	out := new(ServiceImportWeightMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceImportWeightMap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceImportWeightMapList) DeepCopyInto(out *ServiceImportWeightMapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceImportWeightMap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceImportWeightMapList.
func (in *ServiceImportWeightMapList) DeepCopy() *ServiceImportWeightMapList {
	if in == nil {
		return nil
	}
	out := new(ServiceImportWeightMapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceImportWeightMapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceImportWeightMapSpec) DeepCopyInto(out *ServiceImportWeightMapSpec) {
	*out = *in
	if in.SourceClusterWeightMap != nil {
		in, out := &in.SourceClusterWeightMap, &out.SourceClusterWeightMap
		*out = make(map[string]*ClusterWeightMap, len(*in))
		for key, val := range *in {
			var outVal *ClusterWeightMap
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(ClusterWeightMap)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceImportWeightMapSpec.
func (in *ServiceImportWeightMapSpec) DeepCopy() *ServiceImportWeightMapSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceImportWeightMapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceWeightMap) DeepCopyInto(out *ServiceWeightMap) {
	*out = *in
	if in.TargetClusterWeightMap != nil {
		in, out := &in.TargetClusterWeightMap, &out.TargetClusterWeightMap
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceWeightMap.
func (in *ServiceWeightMap) DeepCopy() *ServiceWeightMap {
	if in == nil {
		return nil
	}
	out := new(ServiceWeightMap)
	in.DeepCopyInto(out)
	return out
}
