---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.12"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.13"
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: "release-0.14"
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # Our own dependencies are handled during releases
      - dependency-name: github.com/submariner-io/*
      # These are included by k8s.io/client-go
      - dependency-name: k8s.io/api
      - dependency-name: k8s.io/apimachinery
  - package-ecosystem: gomod
    directory: "/coredns"
    schedule:
      interval: weekly
    ignore:
      # Our own dependencies are handled during releases
      - dependency-name: github.com/submariner-io/*
      # These are included by k8s.io/client-go
      - dependency-name: k8s.io/api
      - dependency-name: k8s.io/apimachinery
