---
linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      #- performance
      - style
  gocyclo:
    min-complexity: 15
  govet:
    enable:
      - fieldalignment
  lll:
    line-length: 140
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    # - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    # - testpackage
    - typecheck
    - unconvert
    # - unparam
    - unused
    - varcheck
    - whitespace
    - wsl
issues:
  exclude-rules:
    # Separating explicit var declarations by blank lines seems excessive.
    - linters:
        - wsl
      text: "declarations should never be cuddled"

    # This rule incorrectly flags code where two logically-related lines are
    # followed by an if conditional to check their err return.
    - linters:
        - wsl
      text: "only one cuddle assignment allowed before if statement"

    # Allow dot imports for tests
    - linters:
        - stylecheck
      path: test/*
      text: "ST1001: should not use dot imports"

    # Ignore pointer bytes in struct alignment tests (this is a very
    # minor optimisation)
    - linters:
        - govet
      text: "pointer bytes could be"
