---
# Licenses other than Apache-2.0 are governed by
# https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
# Note that Allowlist also requires that projects were created
# on GitHub at least 12 months prior and have at least 10 stars
# or 10 forks
allow:
  - "Apache-2.0"
  - "BSD-2-Clause"
  - "BSD-2-Clause-FreeBSD"
  - "BSD-3-Clause"
  - "MIT"
  - "ISC"
  - "Python-2.0"
  - "PostgreSQL"
  - "X11"
  - "Zlib"

override:
  - path: "github.com/flynn/go-shlex"
    licenses: ["Apache-2.0"]
  - path: "../"
    licenses: ["Apache-2.0"]
  - path: "sigs.k8s.io/yaml"
    licenses: ["Apache-2.0", "MIT"]

# Check https://github.com/cncf/foundation/blob/main/license-exceptions/CNCF-licensing-exceptions.csv
exceptions:
  licenseNotPermitted:
    - path: "github.com/hashicorp/errwrap"
      licenses: ["MPL-2.0"]
    - path: "github.com/hashicorp/go-multierror"
      licenses: ["MPL-2.0"]
