/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/submariner-io/lighthouse/pkg/apis/lighthouse.submariner.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServiceImportWeightses implements ServiceImportWeightsInterface
type FakeServiceImportWeightses struct {
	Fake *FakeLighthouseV1alpha1
	ns   string
}

var serviceimportweightsesResource = schema.GroupVersionResource{Group: "lighthouse.submariner.io", Version: "v1alpha1", Resource: "serviceimportweightses"}

var serviceimportweightsesKind = schema.GroupVersionKind{Group: "lighthouse.submariner.io", Version: "v1alpha1", Kind: "ServiceImportWeights"}

// Get takes name of the serviceImportWeights, and returns the corresponding serviceImportWeights object, and an error if there is any.
func (c *FakeServiceImportWeightses) Get(name string, options v1.GetOptions) (result *v1alpha1.ServiceImportWeights, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(serviceimportweightsesResource, c.ns, name), &v1alpha1.ServiceImportWeights{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceImportWeights), err
}

// List takes label and field selectors, and returns the list of ServiceImportWeightses that match those selectors.
func (c *FakeServiceImportWeightses) List(opts v1.ListOptions) (result *v1alpha1.ServiceImportWeightsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(serviceimportweightsesResource, serviceimportweightsesKind, c.ns, opts), &v1alpha1.ServiceImportWeightsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ServiceImportWeightsList{ListMeta: obj.(*v1alpha1.ServiceImportWeightsList).ListMeta}
	for _, item := range obj.(*v1alpha1.ServiceImportWeightsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceImportWeightses.
func (c *FakeServiceImportWeightses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(serviceimportweightsesResource, c.ns, opts))

}

// Create takes the representation of a serviceImportWeights and creates it.  Returns the server's representation of the serviceImportWeights, and an error, if there is any.
func (c *FakeServiceImportWeightses) Create(serviceImportWeights *v1alpha1.ServiceImportWeights) (result *v1alpha1.ServiceImportWeights, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(serviceimportweightsesResource, c.ns, serviceImportWeights), &v1alpha1.ServiceImportWeights{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceImportWeights), err
}

// Update takes the representation of a serviceImportWeights and updates it. Returns the server's representation of the serviceImportWeights, and an error, if there is any.
func (c *FakeServiceImportWeightses) Update(serviceImportWeights *v1alpha1.ServiceImportWeights) (result *v1alpha1.ServiceImportWeights, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(serviceimportweightsesResource, c.ns, serviceImportWeights), &v1alpha1.ServiceImportWeights{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceImportWeights), err
}

// Delete takes name of the serviceImportWeights and deletes it. Returns an error if one occurs.
func (c *FakeServiceImportWeightses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(serviceimportweightsesResource, c.ns, name), &v1alpha1.ServiceImportWeights{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceImportWeightses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(serviceimportweightsesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ServiceImportWeightsList{})
	return err
}

// Patch applies the patch and returns the patched serviceImportWeights.
func (c *FakeServiceImportWeightses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ServiceImportWeights, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(serviceimportweightsesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ServiceImportWeights{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ServiceImportWeights), err
}
