apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        log
        kubernetes cluster2.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           #fallthrough in-addr.arpa ip6.arpa
           fallthrough
        }
        lighthouse cluster2.local cluster3.local {
           fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
