apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dnstools
  name: dnstools
  selfLink: /api/v1/namespaces/default/pods/dnstools
spec:
  containers:
  - image: infoblox/dnstools:latest
    imagePullPolicy: Always
    name: dnstools
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
