/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/submariner-io/lighthouse/pkg/apis/multiclusterservice/v1"
	scheme "github.com/submariner-io/lighthouse/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MultiClusterServicesGetter has a method to return a MultiClusterServiceInterface.
// A group's client should implement this interface.
type MultiClusterServicesGetter interface {
	MultiClusterServices(namespace string) MultiClusterServiceInterface
}

// MultiClusterServiceInterface has methods to work with MultiClusterService resources.
type MultiClusterServiceInterface interface {
	Create(*v1.MultiClusterService) (*v1.MultiClusterService, error)
	Update(*v1.MultiClusterService) (*v1.MultiClusterService, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.MultiClusterService, error)
	List(opts metav1.ListOptions) (*v1.MultiClusterServiceList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.MultiClusterService, err error)
	MultiClusterServiceExpansion
}

// multiClusterServices implements MultiClusterServiceInterface
type multiClusterServices struct {
	client rest.Interface
	ns     string
}

// newMultiClusterServices returns a MultiClusterServices
func newMultiClusterServices(c *LighthouseV1Client, namespace string) *multiClusterServices {
	return &multiClusterServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the multiClusterService, and returns the corresponding multiClusterService object, and an error if there is any.
func (c *multiClusterServices) Get(name string, options metav1.GetOptions) (result *v1.MultiClusterService, err error) {
	result = &v1.MultiClusterService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MultiClusterServices that match those selectors.
func (c *multiClusterServices) List(opts metav1.ListOptions) (result *v1.MultiClusterServiceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.MultiClusterServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested multiClusterServices.
func (c *multiClusterServices) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("multiclusterservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a multiClusterService and creates it.  Returns the server's representation of the multiClusterService, and an error, if there is any.
func (c *multiClusterServices) Create(multiClusterService *v1.MultiClusterService) (result *v1.MultiClusterService, err error) {
	result = &v1.MultiClusterService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("multiclusterservices").
		Body(multiClusterService).
		Do().
		Into(result)
	return
}

// Update takes the representation of a multiClusterService and updates it. Returns the server's representation of the multiClusterService, and an error, if there is any.
func (c *multiClusterServices) Update(multiClusterService *v1.MultiClusterService) (result *v1.MultiClusterService, err error) {
	result = &v1.MultiClusterService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("multiclusterservices").
		Name(multiClusterService.Name).
		Body(multiClusterService).
		Do().
		Into(result)
	return
}

// Delete takes name of the multiClusterService and deletes it. Returns an error if one occurs.
func (c *multiClusterServices) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multiclusterservices").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *multiClusterServices) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multiclusterservices").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched multiClusterService.
func (c *multiClusterServices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.MultiClusterService, err error) {
	result = &v1.MultiClusterService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("multiclusterservices").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
