#!/bin/bash
set -e

source ${SCRIPTS_DIR}/lib/debug_functions
source ${SCRIPTS_DIR}/lib/version

cd ${DAPPER_SOURCE}

binary=bin/lighthouse-agent
extra_flags="$@"

${SCRIPTS_DIR}/compile.sh $binary ./pkg/agent/main.go

cd ./package
cp ../$binary .

${SCRIPTS_DIR}/build_image.sh -i lighthouse-agent -f Dockerfile ${extra_flags}

# clean up agent image
rm lighthouse-agent
