#!/bin/bash
set -e

source $(dirname $0)/version
source $(dirname $0)/../scripts/lib/debug_functions

cd $(dirname $0)/..
mkdir -p bin
echo Building lighthouse-controller version $VERSION
go mod vendor
GO111MODULE=on CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION" -o bin/lighthouse-controller ./pkg/main.go
scripts/package
