#!/bin/bash
set -e

source $(dirname $0)/../scripts/lib/version
source $(dirname $0)/../scripts/lib/debug_functions

extra_flags="$@"

cd $(dirname $0)/..
mkdir -p bin
echo Building lighthouse-agent version ${VERSION}
go mod vendor
GO111MODULE=on CGO_ENABLED=0 go build -ldflags "-X main.VERSION=${VERSION}" -o bin/lighthouse-agent ./pkg/agent/main.go

cd ./package
cp ../bin/lighthouse-agent lighthouse-agent

${SCRIPTS_DIR}/build_image.sh -i lighthouse-agent -f Dockerfile ${extra_flags}

# clean up agent image
rm lighthouse-agent
