#!/bin/bash
set -e

source $(dirname $0)/../scripts/lib/debug_functions

cd $(dirname $0)

if [[ $1 != clean ]]; then
    if [[ $4 = dnsserver ]]; then
        ./build-dnsserver "$@"
    else
       ./build-coredns "$@"
    fi
    ./build-agent "$@"
fi
