#!/bin/bash
set -e

source $(dirname $0)/../scripts/lib/version
source $(dirname $0)/../scripts/lib/debug_functions

cd $(dirname $0)/..
mkdir -p bin
echo Building lighthouse-dnsserver version ${VERSION}
go mod vendor
GO111MODULE=on CGO_ENABLED=0 go build -ldflags "-X main.VERSION=${VERSION}" -o bin/lighthouse-dnsserver ./pkg/dnsserver/main.go

LIGHTHOUSE_DNSSERVER_IMAGE=lighthouse-dnsserver:${VERSION}
cd ./package
cp ../bin/lighthouse-dnsserver lighthouse-dnsserver
docker build -t ${LIGHTHOUSE_DNSSERVER_IMAGE} -f Dockerfile.dnsserver .

echo "Built lighthouse-dnsserver to image: ${LIGHTHOUSE_DNSSERVER_IMAGE}"

# clean up dnsserver image
rm lighthouse-dnsserver
