#!/bin/bash
set -e

source $(dirname $0)/../scripts/lib/debug_functions

cd $(dirname $0)

echo $1

echo $2

echo $3

echo $4

echo $5

echo $6

echo $lhmod

if [[ $1 = clean ]]; then
    ./../scripts/kind-e2e/e2e.sh clean
else
    if [[ $4 = dnsserver ]]; then
        ./build-dnsserver "$@"
    else
       ./build-coredns "$@"
    fi
    ./build-controller "$@"
    ./../scripts/kind-e2e/e2e.sh "$@"
fi
