#!/bin/bash
set -e

cd $(dirname $0)

# ./build
# ./package

export KUBECONFIG=$(echo $(git rev-parse --show-toplevel)/submariner/output/kind-config/dapper/kind-config-cluster{1..3} | sed 's/ /:/g')

cd ../test/e2e

go test -args -ginkgo.v -ginkgo.randomizeAllSpecs \
        -dp-context cluster2 -dp-context cluster3  \
        -report-dir ${DAPPER_SOURCE}/${DAPPER_OUTPUT}/junit 2>&1 | \
        tee ${DAPPER_SOURCE}/${DAPPER_OUTPUT}/e2e-tests.log

