#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-submariner-io}

cd $(dirname $0)

cd ../package

cp ../bin/lighthouse-controller lighthouse-controller

IMAGE=${REPO}/lighthouse-controller:${TAG}
LIGHTHOUSE_IMAGE=${REPO}/lighthouse-controller:${TAG}

docker build -t ${IMAGE} .

echo "Built lighthouse-controller to image: ${IMAGE}"

# clean up controller image
rm lighthouse-controller