ARG BASE_BRANCH=release-0.24
ARG SOURCE=/go/src/github.com/submariner-io/lighthouse

FROM --platform=${BUILDPLATFORM} registry.redhat.io/ubi9/go-toolset:latest AS builder
ARG SOURCE
ARG TARGETPLATFORM
ARG BASE_BRANCH

ENV GOEXPERIMENT=strictfipsruntime
ARG BUILD_TAGS="strictfipsruntime"

COPY . ${SOURCE}

USER root
RUN chown -R 1001:0 ${SOURCE}
USER 1001

RUN git config --global --add safe.directory ${SOURCE}

WORKDIR ${SOURCE}

RUN CGO_ENABLED=1 GOARCH=${TARGETPLATFORM##*/} go build \
    -ldflags "-s -w \
    -X main.version=${BASE_BRANCH}" \
    -tags "${BUILD_TAGS}" \
    -v -o ${SOURCE}/bin/${TARGETPLATFORM}/lighthouse-agent \
    ${SOURCE}/pkg/agent/main.go

FROM --platform=${TARGETPLATFORM} registry.redhat.io/ubi9:latest
ARG BASE_BRANCH
ARG SOURCE
ARG TARGETPLATFORM

RUN adduser -r -l -u 1001 -G root lighthouse

WORKDIR /var/submariner

COPY --from=builder \
    ${SOURCE}/bin/${TARGETPLATFORM}/lighthouse-agent \
    /usr/local/bin/

RUN chown -Rc lighthouse:root /usr/local/bin
RUN chmod -Rc 775 /usr/local/bin

COPY --from=builder ${SOURCE}/LICENSE /licenses/LICENSE

USER lighthouse

ENTRYPOINT ["/usr/local/bin/lighthouse-agent", "-alsologtostderr"]

LABEL com.redhat.component="lighthouse-agent-container" \
      name="rhacm2/lighthouse-agent-rhel9" \
      version="v0.24.1" \
      summary="Lighthouse Agent" \
      description="The Lighthouse Agent provides service discovery for Submariner." \
      io.k8s.display-name="Lighthouse Agent" \
      io.k8s.description="The Lighthouse Agent handles cross-cluster service discovery." \
      io.openshift.tags="submariner, lighthouse-agent, rhacm" \
      maintainer="multi-cluster-networking@redhat.com" \
      com.github.url="https://github.com/submariner-io/lighthouse" \
      com.github.commit="${BASE_BRANCH}" \
      cpe="cpe:/a:redhat:acm:2.17::el9"
