FROM fedora:30

WORKDIR /var/submariner

COPY lighthouse-dnsserver.sh /usr/local/bin

RUN chmod +x /usr/local/bin/lighthouse-dnsserver.sh

COPY lighthouse-dnsserver /usr/local/bin

ENTRYPOINT lighthouse-dnsserver.sh

