ARG BASE_BRANCH=release-0.23
ARG SOURCE=/go/src/github.com/submariner-io/lighthouse

FROM --platform=${BUILDPLATFORM} registry.redhat.io/ubi10/go-toolset:latest AS builder
ARG SOURCE
ARG TARGETPLATFORM
ARG BASE_BRANCH

ENV GOEXPERIMENT=strictfipsruntime
ARG BUILD_TAGS="strictfipsruntime"

COPY . ${SOURCE}

USER root
RUN chown -R 1001:0 ${SOURCE}
USER 1001

RUN git config --global --add safe.directory ${SOURCE}

WORKDIR ${SOURCE}/coredns

RUN CGO_ENABLED=1 GOARCH=${TARGETPLATFORM##*/} go build \
    -ldflags "-s -w \
    -X main.version=${BASE_BRANCH}" \
    -tags "${BUILD_TAGS}" \
    -v -o ${SOURCE}/bin/${TARGETPLATFORM}/lighthouse-coredns \
    .

FROM --platform=${TARGETPLATFORM} registry.redhat.io/ubi10:latest
ARG BASE_BRANCH
ARG SOURCE
ARG TARGETPLATFORM

RUN adduser -r -l -u 1001 -G root lighthouse

COPY --from=builder \
    ${SOURCE}/bin/${TARGETPLATFORM}/lighthouse-coredns \
    /usr/local/bin/

RUN chown -Rc lighthouse:root /usr/local/bin
RUN chmod -Rc 775 /usr/local/bin

# Linux capability for enabling port 53
RUN setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/lighthouse-coredns

COPY --from=builder ${SOURCE}/LICENSE /licenses/LICENSE

USER lighthouse

EXPOSE 53 53/udp

ENTRYPOINT ["/usr/local/bin/lighthouse-coredns"]

LABEL com.redhat.component="lighthouse-coredns-container" \
      name="rhacm2/lighthouse-coredns-rhel10" \
      version="v0.23.0" \
      summary="Lighthouse CoreDNS" \
      description="The Lighthouse CoreDNS provides DNS resolution for cross-cluster services." \
      io.k8s.display-name="Lighthouse CoreDNS" \
      io.k8s.description="The Lighthouse CoreDNS provides DNS resolution for cross-cluster services." \
      io.openshift.tags="submariner, lighthouse-coredns, rhacm" \
      maintainer="multi-cluster-networking@redhat.com" \
      com.github.url="https://github.com/submariner-io/lighthouse" \
      com.github.commit="${BASE_BRANCH}" \
      cpe="cpe:/a:redhat:acm:2.16::el10"
