FROM debian:stable-slim

RUN apt-get update && apt-get -y install ca-certificates && update-ca-certificates

COPY bin/lighthouse-coredns /usr/local/bin/

EXPOSE 53 53/udp

ENTRYPOINT ["/usr/local/bin/lighthouse-coredns"]
