FROM debian:stable-slim

RUN apt-get update && apt-get -y install ca-certificates && update-ca-certificates

FROM scratch

COPY --from=0 /etc/ssl/certs /etc/ssl/certs
COPY bin/lighthouse-coredns /usr/local/bin/

EXPOSE 53 53/udp

ENTRYPOINT ["/usr/local/bin/lighthouse-coredns"]
