apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-controller
  namespace: kube-federation-system
  labels:
    app: lighthouse-controller
spec:
  selector:
    matchLabels:
      app: lighthouse-controller
  template:
    metadata:
      labels:
        app: lighthouse-controller
    spec:
      containers:
      - name: lighthouse-controller
        image: lighthouse-controller:local
      serviceAccount: kubefed-controller     # for production we need to create our own service account and
      serviceAccountName: kubefed-controller # provide access to KubeFedClusters
