apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-dnsserver
  namespace: kube-system
  labels:
    app: lighthouse-dnsserver
spec:
  selector:
    matchLabels:
      app: lighthouse-dnsserver
  template:
    metadata:
      labels:
        app: lighthouse-dnsserver
    spec:
      containers:
      - name: lighthouse-dnsserver
        image: lighthouse-dnsserver:local
      serviceAccount: coredns     # for production we need to create our own service account and
      serviceAccountName: coredns # provide access to KubeFedClusters
---
apiVersion: v1
kind: Service
metadata:
  name: lighthouse-dnsserver
  namespace: kube-system
  labels:
    app: lighthouse-dnsserver
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
  - name: udp
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: lighthouse-dnsserver
  type: ClusterIP
