on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v**'

name: End to End Tests
jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        globalnet: ['', '--globalnet']
        deploytool: ['operator', 'helm']
    steps:
      - uses: actions/checkout@master

      - name: Reclaim free space!
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
          free -h

      - name: Run E2E deployment and tests
        env:
          CLUSTERS_ARGS: ${{ matrix.globalnet }}
          DEPLOY_ARGS: ${{ matrix.globalnet }}
        run: |
          make e2e deploytool=${{ matrix.deploytool }}

      - name: Post Mortem
        if: failure()
        run: |
          df -h
          free -h
          make post-mortem
