on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v**'

name: Commit Message Validations
jobs:
  gitlint:
    name: Gitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: make gitlint
